/**
 * Ported from `packages/share/e2e/report/report.cy.ts`.
 *
 * Exercises the report generator end-to-end: the full template validation for a report that
 * contains slow requests and one that does not, the `createNetworkReportFromFile` count, and the
 * pure `generateReport` behaviours (url filtering, loading from a stats file, dropping entries
 * without a duration, tolerating a missing response, per-request high-duration highlighting with a
 * canvas colour check) plus its error handling.
 *
 * Adaptations from the Cypress suite:
 * - The Cypress tests drove a live `cy.interceptor()` (via `getDynamicUrl` + `waitUntilRequestIsDone`)
 *   and Node `cy.task`s to build the report. Following the intended Playwright approach, the report
 *   is generated by calling the library (`generateReport` / `createNetworkReportFromFile`) DIRECTLY
 *   in the test process, writing the HTML into the server's statically-served `fixtures` folder, and
 *   opening it with `page.goto("/fixtures/<name>.html")`.
 * - The "with default settings" (slow requests present) and "with custom settings" (high threshold,
 *   no slow requests) scenarios are reproduced from the shared mock stats file: the default
 *   `highDuration` (3000ms) leaves several slow requests, while a very high threshold produces none.
 * - The Cypress `generateReport - with node environment` tests stubbed `require("fs")` with
 *   `mockRequire` to force `writeFileSync` to throw / `existsSync` to be false. Those are
 *   Cypress-plumbing-specific; the intent ("throws on error", "creates the directory") is preserved
 *   here with real Node behaviour: reading a missing stats file throws, and writing into a
 *   non-existent directory creates it.
 * - `cy.get(...).invoke("text")` -> `await locator.innerText()`; `.should("have.class", c)` ->
 *   `toHaveClass(/c/)`; `.should("contain.text", t)` -> `toContainText(t)`.
 * - `checkBarColor` reads a canvas pixel via `page.evaluate` (see `./checkBarColor`).
 */

import * as fs from "fs";
import * as path from "path";
import {
    CallStack,
    createNetworkReportFromFile,
    expect,
    generateReport,
    ReportClassName,
    ReportTestId,
    test
} from "playwright-interceptor";

import { byDataTestId } from "../../src/selectors";
import { checkBarColor } from "./checkBarColor";
import { validateReportTemplate } from "./validateReportTemplate";

const mockFolderPath = path.resolve(__dirname, "../../../share/mock");
const mockStatsPath = path.join(mockFolderPath, "sources.stats.json");
const fixturesFolder = path.resolve(__dirname, "../../../server/fixtures");

const fixtureUrl = (fileName: string) => `/fixtures/${fileName}`;

/**
 * Write a stats JSON file (the format `generateReport` / `createNetworkReportFromFile` load from
 * disk) and return its path.
 *
 * The file is written into the caller-provided directory. Tests pass `test.info().outputDir`, which
 * Playwright isolates per test (and cleans before each run), so parallel workers never read, write,
 * or delete each other's scratch files.
 */
const writeStatsFile = (dir: string, fileName: string, entries: unknown[]) => {
    const filePath = path.join(dir, fileName);

    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, JSON.stringify(entries), "utf8");

    return filePath;
};

const getTotalRequests = async (page: import("@playwright/test").Page) => {
    const text = await page.locator(byDataTestId(ReportTestId.TOTAL_REQUESTS_CARD)).innerText();

    return parseInt(text);
};

const statsJsonEntry = (url: string, duration?: number, withResponse = true) => ({
    crossDomain: false,
    ...(duration !== undefined ? { duration } : {}),
    isPending: false,
    request: {
        body: "",
        headers: { "content-type": "application/json" },
        method: "POST",
        query: { duration: "1000", path: "/api/test2" }
    },
    resourceType: "fetch",
    ...(withResponse
        ? {
              response: {
                  body: "{}",
                  headers: {},
                  isMock: false,
                  statusCode: 200,
                  statusText: "OK",
                  timeEnd: new Date().toISOString()
              }
          }
        : {}),
    timeStart: new Date().toISOString(),
    url
});

const callStackEntry = (url: URL, duration: number, sequenceId: number): CallStack => ({
    crossDomain: false,
    duration,
    isPending: false,
    request: {
        body: "",
        headers: { "content-type": "application/json" },
        method: "POST",
        query: {}
    },
    resourceType: "fetch",
    response: {
        body: "{}",
        headers: {},
        isMock: false,
        statusCode: 200,
        statusText: "OK",
        timeEnd: new Date()
    },
    runtime: 0,
    runtimeString: "0h 0m 0s 0ms",
    sequenceId,
    timeStart: new Date(),
    url
});

test.describe("Report", () => {
    test.describe("With default settings", () => {
        test("Should create a report with slow requests", async ({ page }) => {
            test.setTimeout(60000);

            const fileName = "report-default.html";

            createNetworkReportFromFile(mockStatsPath, {
                fileName: "report-default",
                outputDir: fixturesFolder
            });

            await page.goto(fixtureUrl(fileName));

            // The default `highDuration` (3000ms) leaves several slow requests in the mock.
            await validateReportTemplate(page, true);
        });
    });

    test.describe("With custom settings", () => {
        test("Should create a report without slow requests", async ({ page }) => {
            test.setTimeout(60000);

            const fileName = "report-custom.html";

            createNetworkReportFromFile(mockStatsPath, {
                fileName: "report-custom",
                highDuration: 100000,
                outputDir: fixturesFolder
            });

            await page.goto(fixtureUrl(fileName));

            // A very high threshold means no request is considered slow.
            await validateReportTemplate(page, false);
        });
    });

    test.describe("createNetworkReportFromFile", () => {
        test("Should create a report from a file", async ({ page }) => {
            const statsPath = writeStatsFile(test.info().outputDir, "createFromFile.stats.json", [
                statsJsonEntry("http://localhost:3000/api/test1", 200),
                statsJsonEntry("http://localhost:3000/api/test2", 1000),
                statsJsonEntry("http://localhost:3000/api/test3", 300)
            ]);

            const outputFilePath = createNetworkReportFromFile(statsPath, {
                outputDir: fixturesFolder
            });

            expect(fs.existsSync(outputFilePath)).toBe(true);

            await page.goto(fixtureUrl(path.basename(outputFilePath)));

            expect(await getTotalRequests(page)).toEqual(3);
        });
    });

    test.describe("generateReport", () => {
        test("Should filter the entries by url", async ({ page }) => {
            const apiTest1 = new URL("http://localhost:3000/api/test1");
            const apiTest2 = new URL("http://localhost:3000/api/test2");

            const fileName = "report-filter-by-url.html";
            const outputFilePath = path.join(fixturesFolder, fileName);

            generateReport(
                [callStackEntry(apiTest1, 1000, 1), callStackEntry(apiTest2, 1000, 2)],
                outputFilePath,
                {
                    filter: (dataPoint) => dataPoint.url.pathname === apiTest1.pathname
                }
            );

            await page.goto(fixtureUrl(fileName));

            expect(await getTotalRequests(page)).toEqual(1);
        });

        test("Should load report from file", async ({ page }) => {
            const statsPath = writeStatsFile(test.info().outputDir, "loadFromFile.stats.json", [
                statsJsonEntry("http://localhost:3000/api/test1", 1000)
            ]);

            const fileName = "report-from-file.html";
            const outputFilePath = path.join(fixturesFolder, fileName);

            generateReport(statsPath, outputFilePath);

            await page.goto(fixtureUrl(fileName));

            expect(await getTotalRequests(page)).toEqual(1);
        });

        test("Should filter out the entries with no duration", async ({ page }) => {
            const statsPath = writeStatsFile(test.info().outputDir, "noDuration.stats.json", [
                statsJsonEntry("http://localhost:3000/api/test1")
            ]);

            const fileName = "report-from-file-with-no-duration.html";
            const outputFilePath = path.join(fixturesFolder, fileName);

            generateReport(statsPath, outputFilePath);

            await page.goto(fixtureUrl(fileName));

            expect(await getTotalRequests(page)).toEqual(0);
        });

        test("Should not fail if the response is not defined", async ({ page }) => {
            const statsPath = writeStatsFile(test.info().outputDir, "noResponse.stats.json", [
                statsJsonEntry("http://localhost:3000/api/test1", undefined, false)
            ]);

            const fileName = "report-from-file-with-no-response.html";
            const outputFilePath = path.join(fixturesFolder, fileName);

            generateReport(statsPath, outputFilePath);

            await page.goto(fixtureUrl(fileName));

            expect(await getTotalRequests(page)).toEqual(0);
        });

        test("Should filter the entries by url and highlight the slow ones", async ({ page }) => {
            const apiTest1 = new URL("http://localhost:3000/api/test-1");
            const apiTest2 = new URL("http://localhost:3000/api/test-2");
            const apiTest3 = new URL("http://localhost:3000/api/test-3");

            const fileName = "report-with-highlight.html";
            const outputFilePath = path.join(fixturesFolder, fileName);

            generateReport(
                [
                    callStackEntry(apiTest1, 1500, 1),
                    callStackEntry(apiTest2, 1500, 2),
                    callStackEntry(apiTest3, 1500, 3)
                ],
                outputFilePath,
                {
                    highDuration: (url) => {
                        if (url.pathname === apiTest1.pathname) {
                            return 1000;
                        }

                        if (url.pathname === apiTest3.pathname) {
                            return 2000;
                        }

                        return 0;
                    }
                }
            );

            await page.goto(fixtureUrl(fileName));

            expect(await getTotalRequests(page)).toEqual(3);

            await expect(page.locator(byDataTestId(ReportTestId.LEGEND_SLOW))).toContainText(
                "Custom"
            );

            // The duration cell for apiTest1 (index 0) is highlighted as slow (red)
            await expect(page.locator(byDataTestId("duration-cell", "0"))).toHaveClass(
                new RegExp(ReportClassName.DURATION_SLOW)
            );
            await expect(page.locator(byDataTestId("duration-cell", "1"))).toHaveClass(
                new RegExp(ReportClassName.DURATION_FAST)
            );
            await expect(page.locator(byDataTestId("duration-cell", "2"))).toHaveClass(
                new RegExp(ReportClassName.DURATION_FAST)
            );

            await checkBarColor(page, 0, "red");
            await checkBarColor(page, 1, "green");
            await checkBarColor(page, 2, "green");
        });
    });

    test.describe("generateReport - error handling", () => {
        test("Should throw an error when the stats file cannot be read", () => {
            const outputDir = test.info().outputDir;
            const missing = path.join(outputDir, "does-not-exist.stats.json");

            expect(() => generateReport(missing, path.join(outputDir, "report.html"))).toThrow();
        });

        test("Should create a directory if it doesn't exist", () => {
            // `test.info().outputDir` is isolated and cleaned per test, so the nested directory is
            // guaranteed not to exist yet without deleting a directory shared with other workers.
            const nestedDir = path.join(test.info().outputDir, "nested", "deeper");
            const outputFilePath = path.join(nestedDir, "report.html");

            expect(fs.existsSync(nestedDir)).toBe(false);

            generateReport([], outputFilePath);

            expect(fs.existsSync(outputFilePath)).toBe(true);
        });
    });
});
